# Generated by Django 3.1 on 2020-11-26 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20201126_1448'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user_name', 'course')},
        ),
    ]
