# Generated by Django 3.1 on 2020-11-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201128_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='user_count',
        ),
    ]
