# Generated by Django 3.1 on 2020-11-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_college_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('spring', '春'), ('autumu', '秋')], max_length=100),
        ),
    ]
